### ISSUE TITLE
Penggunaan Database Wilayah Indonesia untuk Pembuatan Lokasi (commit:Validasi Penambahan Kategori dan Lokasi)

### ISSUE THREAD

**Issue by cakman87** [ownner21/hajatku#1]
Untuk menghindari tertambahnya kesalahan saat pembuatan wilayah lokasi dan meningkatkan validitas lokasi yang dapat digunakan user, akan lebih baik jika pembuatan wilayah lokasi diganti menggunakan dropdown wilayah indonesia yang datanya mengambil dari sebuah database.
saya menemukan repository yang terdapat database wilayah indonesia. mungkin databasenya bisa digunakan untuk mengurangi waktu pengerjaan.
link : [k4ng](https://github.com/k4ng/codeigniter-dropdown-wilayah-indonesia)

**Comment by ownner21** [comment]
data terlalu banyak untuk sebuah dummy, apakah anda yakin untuk melanjutkan ke proses selanjutnya??

**Comment by cakman87** [comment]
kalau menggunakan daftar wiilayah yang ada di jawa timur saja bagaimana?
ex: setelah meng-import databasenya, hapus semua data selain wilayah jawa timur

**Comment by ownner21** [comment]
wilayah ini akan dikembangkan jika benar benar area disekitar kita support dengan program ini, karena jika menggunakan data yang terlalu banyak maka mengubah metode pencarian lokasi.

**Comment by cakman87** [comment]
ok, untuk saat ini saya tutup dulu issue ini
