### ISSUE TITLE
Validasi Pendaftaran (commit:whitespce fix)

### ISSUE THREAD

**Issue by cakman87** [ownner21/hajatku#2]
Validasi data pendaftaran masih kurang, karena masih bisa mendaftar dengan email dummy dan password dengan 1 buah karakter saja, sedangkan form login mengharuskan member mengisi minimal 6 karakter.
Member juga bisa mendaftar dengan password blankspace berjumlah minimal 6 karakter, tapi form login tidak bisa membaca password yang terdiri dari blankspace saja.

**Comment by ownner21** [comment]
untuk verifikasi email belum dibuat, validasi blankspace secepatnya diperbaiki

**Comment by cakman87** [comment]
verifikasi sudah berhasil, tapi masih bisa memakai password seperti '123    ' dengan akhiran beberapa blankspace. (apakah ini normal?)

**Comment by ownner21** [comment]
masih belum bisa, bug ini akan diperbaiki suatu saat nanti, karena dirasa tidak begitu mendesak

**Comment by ownner21** [comment]
sudah saya perbaiki silahkan update ke versi terbaru

**Comment by cakman87** [comment]
-sudah saya update ke commit [whitespace](https://github.com/ownner21/hajatku/commit/c877d596191a8350df6ec3960321ce1defea8c13) , tapi saya cek masih berhasil daftar dan login dengan pasword 'q\s\s\s\s\s\s\s'. [fixed](https://github.com/ownner21/hajatku/commit/f1712a6ac0501f2474e3f3041ad0170a6ac708ce)
-saya tidak bisa mendaftar dengan password normal 'firman123' atau '123123123', tapi bisa menggunakan 'asdasdasd' [fixed](https://github.com/ownner21/hajatku/commit/f1712a6ac0501f2474e3f3041ad0170a6ac708ce)

**Comment by ownner21** [comment]
silahkan diperbarui

**Comment by cakman87** [comment]
ok, sudah fixed, saya tutup issue ini
