### ISSUE TITLE
Permasalahan dengan topup (commit:whitespce fix)

### ISSUE THREAD

**Issue by cakman87** [ownner21/hajatku#3]
-Nomor rekening yang muncul pada pop up setelah mengajukan top up tidak cocok dengan info nomor rekening yang disediakan. [fix](https://github.com/ownner21/hajatku/commit/3dfb3af6af1c92bb4b9ef19335898f52dc53a4e2)
-Jika member menekan tombol saldo ketika dia tidak mempunyai saldo, maka halaman akan redirect ke halaman debug karena error. [fix](https://github.com/ownner21/hajatku/commit/74ca5cedd02cd23e1a8166d118d81050b654cff1)
-Jika member mengajukan sebuah topup, nama member yang muncul di halaman admin tidak sesuai [fix](https://github.com/ownner21/hajatku/commit/74ca5cedd02cd23e1a8166d118d81050b654cff1)
-Pengajuan topup tetap dianggap lunas meskipun ditekan tombol gagal di halaman topup admin [fix](https://github.com/ownner21/hajatku/commit/74ca5cedd02cd23e1a8166d118d81050b654cff1)
-Jika pengajuan topup melebihi jumlah member, nama member akan menjadi 'NN' pada halaman topup admin [fix](https://github.com/ownner21/hajatku/commit/74ca5cedd02cd23e1a8166d118d81050b654cff1)
-Nomor rekening yang muncul pada pop up setelah mengajukan top up tidak cocok dengan info nomor rekening yang disediakan. [fix](https://github.com/ownner21/hajatku/commit/74ca5cedd02cd23e1a8166d118d81050b654cff1)

**Comment by ownner21** [comment]
Database bank belum dibuatkan, 
untuk poin selanjutnya sudah saya perbaiki, silahkan melakukan update data (pull)

**Comment by cakman87** [comment]
masih kurang : 
-Nomor rekening yang muncul pada pop up setelah mengajukan top up tidak cocok dengan info nomor rekening yang disediakan. [fixed](https://github.com/ownner21/hajatku/commit/3dfb3af6af1c92bb4b9ef19335898f52dc53a4e2)

**Comment by ownner21** [comment]
struktur bank sudah dibaut db, silahkan dan udah diperbaiki notifnya. silahkan diupdate data terbaru

**Comment by cakman87** [comment]
ok
