### ISSUE TITLE
Permasalahan member (commit:whitespce fix)

### ISSUE THREAD

**Issue by cakman87** [ownner21/hajatku#5]
-member yang diblokir masih bisa ber-operasi seperti biasa [fixed](https://github.com/ownner21/hajatku/commit/9413e4f808d22bb26dc8b33487bc365bb471e11e)
-2 member berbeda bisa login pada browser yang sama pada saat yang bersamaan (session jadi 1) [fixed](https://github.com/ownner21/hajatku/commit/3dfb3af6af1c92bb4b9ef19335898f52dc53a4e2)
-barang di cart yang masih ada pada sesi saat ini akan ada di akun siapapun yang login pada sesi itu juga, sehingga sebuah pemesanan bisa dipesan oleh member A dan dilunasi oleh member B [fixed](https://github.com/ownner21/hajatku/commit/3dfb3af6af1c92bb4b9ef19335898f52dc53a4e2)

**Comment by ownner21** [comment]
session tidak bisa jadi satu, itu memang kelemahan penggunaan session. sistem cart akan segera dirubah ke sistem database, block member sudah aktif, silahakn diupdate aplikasinya

**Comment by cakman87** [comment]
ok, kurang : 
-2 member berbeda bisa login pada browser yang sama pada saat yang bersamaan (Ini normal?) [fixed](https://github.com/ownner21/hajatku/commit/3dfb3af6af1c92bb4b9ef19335898f52dc53a4e2)
-barang di cart yang masih ada pada sesi saat ini akan ada di akun siapapun yang login pada sesi itu juga, sehingga sebuah pemesanan bisa dipesan oleh member A dan dilunasi oleh member B [fixed](https://github.com/ownner21/hajatku/commit/3dfb3af6af1c92bb4b9ef19335898f52dc53a4e2)

**Comment by ownner21** [comment]
database cart sudah saya bentuk silahkan update ke versi terbaru.

**Comment by cakman87** [comment]
ok, saya tutup issue ini
