### ISSUE TITLE
Permasalahan dengan bank (commit: masukkan untuk fix bank)

### ISSUE THREAD

**Issue by cakman87** [ownner21/hajatku#7]
-data type dari nomor rekening menggunakan integer, yang akan menimbulkan error jika admin memasukkan nomor rekening yang melebihi jangkauan dari integer. sebaiknya menggunakan varchar yang divalidasi dengan regex. [fix sementara](https://github.com/ownner21/hajatku/commit/c50e896a3498a96da3a0c5bbda97a3bfbe75ac23)
-member tidak bisa melakukan topup karena field bank menggunakan integer. (error sql) [fix sementara](https://github.com/ownner21/hajatku/commit/c50e896a3498a96da3a0c5bbda97a3bfbe75ac23)

**Comment by cakman87** [comment]
saya akan tutup issue setelah commit disetujui dan dimerge

**Comment by ownner21** [comment]
kalo ganti struktur jangan lupa merubah struktur yang ada di migration. silahkan dirubah ke string. asalkan gk eror gk masalah

**Comment by cakman87** [comment]
ok, sudah fixed, saya tutup issue ini
